### PR TITLE
Fix build error

### LINKED ISSUE #288: Compile error
Related: Swift #3801

[Point of use](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/effa96470083d4d6988bc520f75cb067009773ca/Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift#L83)

Screenshot 2023-03-31 at 16 08 14

### PR DESCRIPTION
**Pull request by dfeinzimer**
Closes #288

### CODE REVIEW

File: Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift [hunk 1]
```diff
@@ -80,12 +80,12 @@ struct AttachmentsPopupElementView: View {
...
         .task {
-            try? await popupElement.fetchAttachments()
-            let attachmentModels = popupElement.attachments.reversed().map { attachment in
-                AttachmentModel(attachment: attachment)
+            if let attachmentModels = try? await popupElement.attachments.reversed().map({ 
+                AttachmentModel(attachment: $0)
+            }) {
+                viewModel.attachmentModels.append(contentsOf: attachmentModels)
+                isLoadingAttachments = false
             }
```
Comment (mhdostal) [inline Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift:88]: I like this a little better because it always sets `viewModel.attachmentModels` and always sets `isLoadingAttachments` to false.
```suggestion
            let attachmentModels = try? await popupElement.attachments.reversed().map { attachment in
                AttachmentModel(attachment: attachment)
            }
            viewModel.attachmentModels.append(contentsOf: attachmentModels ?? [])
            isLoadingAttachments = false
```

**Review by mhdostal — CHANGES_REQUESTED** [review]

**Review by mhdostal — APPROVED** [review]
